#!/usr/bin/env php
<?php
defined('SIGTERM') || define('SIGTERM', 15); //中止服务
//declare(ticks = 1);

// Only for cli.
if (PHP_SAPI !== 'cli') {
    exit("Only run in command line mode \n");
}
if (!function_exists("socket_create")) {
    exit("Please install php_sockets extension \n");
}

//定义时间区
date_default_timezone_set("PRC");
//strtoupper(substr(PHP_OS, 0, 3))==='WIN' || "CYGWIN" == PHP_OS
define('IS_WINDOWS', DIRECTORY_SEPARATOR === '\\');
//根目录
define("HOME", __DIR__);

//初始化日志目录
if (!is_dir(__DIR__."/logs")) {
    mkdir(__DIR__."/logs");
}

include __DIR__."/src/helpers.php";

//初始化命令行参数 $argc — 传递给脚本的参数数目
$str_argv = '';
for ($i = 1; $i < $argc; $i++) {
    $str_argv .= ' '.$argv[$i];
}

$command_line = 'php '.basename(__FILE__).' '.$str_argv;
define("WING_COMMAND_LINE", $command_line);

if (!file_exists(__DIR__."/composer.json")) {
    copy(__DIR__."/composer.json.init", __DIR__."/composer.json");
}

if (!file_exists(__DIR__.'/vendor/autoload.php')) {
    echo "正在尝试安装依赖-composer install", PHP_EOL;
    exec("composer install");
//    echo PHP_EOL, "请重新执行：", WING_COMMAND_LINE, PHP_EOL;
//    exit;
}

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/windows.php';

use Symfony\Component\Console\Application;

//初始化开发模式 $argv — 传递给脚本的参数数组
$debug = false;
foreach ($argv as $item) {
    if (strpos($item, "debug") !== false) {
		$debug = true;
    }

    if (strpos($item, "restart") !== false) {
        $winfo  = \Wing\Library\Worker::getWorkerProcessInfo();
        $debug  = $winfo["debug"];
    }
}
define("WING_DEBUG", $debug);

if (WING_DEBUG) {
	ini_set("display_errors", "On");
	error_reporting(E_ALL);
}

try {
    $application = new Application("wing-binlog");
    $application->setCatchExceptions(true); //在命令执行期间开启异常捕获

    $commands = [
        \Wing\Command\ServerStart::class,
        \Wing\Command\ServerStop::class,
        \Wing\Command\ServerVersion::class,
        \Wing\Command\ServerStatus::class,
        \Wing\Command\Help::class,
        \Wing\Command\ServerRestart::class
    ];
    foreach ($commands as $command) {
        $application->add(new $command);
    }

    $application->run();
} catch (\Exception $e) {
    echo sprintf('line:%s, file:%s, err:%s', $e->getLine(), $e->getFile(), $e->getMessage()),PHP_EOL;
    wing_log('exception', $e->getLine(), $e->getFile(), $e->getMessage(), $e->getTraceAsString());
}